branches:
  only:
    - master
language: objective-c
osx_image: xcode7.3
script: xctool -project A_IOSHelper.xcodeproj -scheme A_IOSHelper -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
#script: xctool -project A_IOSHelper.xcodeproj -scheme A_IOSHelper -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO test GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES clean build
after_success:
  bash <(curl -s https://codecov.io/bash)